# Cross-validation tests for R/kernel_pca.R against Python sklearn/scipy.
#
# Reference fixture generated by tests/generate_kernel_pca_fixture.py using
# sklearn.decomposition.KernelPCA (which internally calls scipy.linalg.eigh).


# ---------------------------------------------------------------------------
# Helper: load first 100 DASH TCRs
# ---------------------------------------------------------------------------
.load_dash_100 <- function() {
    dash_path <- test_path("fixtures", "dash.csv")
    if (!file.exists(dash_path)) return(NULL)
    dash <- read.csv(dash_path, stringsAsFactors = FALSE, nrows = 100)
    data.frame(
        va    = dash$v_a_gene,
        ja    = dash$j_a_gene,
        cdr3a = dash$cdr3_a_aa,
        vb    = dash$v_b_gene,
        jb    = dash$j_b_gene,
        cdr3b = dash$cdr3_b_aa,
        stringsAsFactors = FALSE
    )
}


# ---------------------------------------------------------------------------
# Test 1: Eigenvalues match scipy (default kernel)
# ---------------------------------------------------------------------------

test_that("eigenvalues match Python/scipy reference (default kernel)", {
    fixture_path <- test_path("fixtures", "kernel_pca_ref.json")
    skip_if_not(file.exists(fixture_path),
                "Run generate_kernel_pca_fixture.py first")
    dash_path <- test_path("fixtures", "dash.csv")
    skip_if_not(file.exists(dash_path), "dash.csv not found")
    skip_if_not_installed("jsonlite")

    ref <- jsonlite::fromJSON(fixture_path, simplifyVector = TRUE)
    tcrs <- .load_dash_100()
    skip_if(is.null(tcrs), "Could not load DASH data")

    expect_equal(nrow(tcrs), ref$n)

    result <- compute_tcrdist_kernel_pca(
        tcrs, ref$organism,
        n_components = ref$n_components,
        kernel = NULL,
        method = "eigen"
    )

    py_eigenvalues <- ref$default_kernel$eigenvalues

    expect_true(result$n_components >= length(py_eigenvalues),
                info = sprintf("R returned %d components, Python had %d",
                               result$n_components, length(py_eigenvalues)))

    r_eigenvalues <- result$eigenvalues[seq_along(py_eigenvalues)]
    expect_equal(r_eigenvalues, py_eigenvalues, tolerance = 1e-10,
                 label = "default kernel eigenvalues")
})


# ---------------------------------------------------------------------------
# Test 2: Embeddings match scipy (default kernel, modulo sign flip)
# ---------------------------------------------------------------------------

test_that("embeddings match Python/scipy reference (default kernel, modulo sign flip)", {
    fixture_path <- test_path("fixtures", "kernel_pca_ref.json")
    skip_if_not(file.exists(fixture_path),
                "Run generate_kernel_pca_fixture.py first")
    dash_path <- test_path("fixtures", "dash.csv")
    skip_if_not(file.exists(dash_path), "dash.csv not found")
    skip_if_not_installed("jsonlite")

    ref <- jsonlite::fromJSON(fixture_path, simplifyVector = TRUE)
    tcrs <- .load_dash_100()
    skip_if(is.null(tcrs), "Could not load DASH data")

    result <- compute_tcrdist_kernel_pca(
        tcrs, ref$organism,
        n_components = ref$n_components,
        kernel = NULL,
        method = "eigen"
    )

    py_embeddings <- ref$default_kernel$embeddings
    n_comp <- ncol(py_embeddings)

    for (k in seq_len(n_comp)) {
        r_col  <- result$embeddings[, k]
        py_col <- py_embeddings[, k]

        expect_equal(
            abs(r_col), abs(py_col), tolerance = 1e-8,
            info = sprintf("default kernel embedding component %d (abs values)", k)
        )

        if (sd(py_col) > 1e-12) {
            r <- cor(r_col, py_col)
            expect_true(
                abs(abs(r) - 1) < 1e-6,
                info = sprintf(
                    "default kernel component %d: |cor| = %.10f (expected ~1)",
                    k, abs(r)
                )
            )
        }
    }
})


# ---------------------------------------------------------------------------
# Test 3: Eigenvalues match scipy (gaussian kernel)
# ---------------------------------------------------------------------------

test_that("eigenvalues match Python/scipy reference (gaussian kernel)", {
    fixture_path <- test_path("fixtures", "kernel_pca_ref.json")
    skip_if_not(file.exists(fixture_path),
                "Run generate_kernel_pca_fixture.py first")
    dash_path <- test_path("fixtures", "dash.csv")
    skip_if_not(file.exists(dash_path), "dash.csv not found")
    skip_if_not_installed("jsonlite")

    ref <- jsonlite::fromJSON(fixture_path, simplifyVector = TRUE)
    tcrs <- .load_dash_100()
    skip_if(is.null(tcrs), "Could not load DASH data")

    result <- compute_tcrdist_kernel_pca(
        tcrs, ref$organism,
        n_components = ref$n_components,
        kernel = "gaussian",
        gaussian_kernel_sdev = ref$gaussian_kernel$sdev,
        method = "eigen"
    )

    py_eigenvalues <- ref$gaussian_kernel$eigenvalues

    expect_true(result$n_components >= length(py_eigenvalues),
                info = sprintf("R returned %d components, Python had %d",
                               result$n_components, length(py_eigenvalues)))

    r_eigenvalues <- result$eigenvalues[seq_along(py_eigenvalues)]
    expect_equal(r_eigenvalues, py_eigenvalues, tolerance = 1e-10,
                 label = "gaussian kernel eigenvalues")
})


# ---------------------------------------------------------------------------
# Test 4: Embeddings match scipy (gaussian kernel, modulo sign flip)
# ---------------------------------------------------------------------------

test_that("embeddings match Python/scipy reference (gaussian kernel, modulo sign flip)", {
    fixture_path <- test_path("fixtures", "kernel_pca_ref.json")
    skip_if_not(file.exists(fixture_path),
                "Run generate_kernel_pca_fixture.py first")
    dash_path <- test_path("fixtures", "dash.csv")
    skip_if_not(file.exists(dash_path), "dash.csv not found")
    skip_if_not_installed("jsonlite")

    ref <- jsonlite::fromJSON(fixture_path, simplifyVector = TRUE)
    tcrs <- .load_dash_100()
    skip_if(is.null(tcrs), "Could not load DASH data")

    result <- compute_tcrdist_kernel_pca(
        tcrs, ref$organism,
        n_components = ref$n_components,
        kernel = "gaussian",
        gaussian_kernel_sdev = ref$gaussian_kernel$sdev,
        method = "eigen"
    )

    py_embeddings <- ref$gaussian_kernel$embeddings
    n_comp <- ncol(py_embeddings)

    for (k in seq_len(n_comp)) {
        r_col  <- result$embeddings[, k]
        py_col <- py_embeddings[, k]

        expect_equal(
            abs(r_col), abs(py_col), tolerance = 1e-8,
            info = sprintf("gaussian kernel embedding component %d (abs values)", k)
        )

        if (sd(py_col) > 1e-12) {
            r <- cor(r_col, py_col)
            expect_true(
                abs(abs(r) - 1) < 1e-6,
                info = sprintf(
                    "gaussian kernel component %d: |cor| = %.10f (expected ~1)",
                    k, abs(r)
                )
            )
        }
    }
})


# ---------------------------------------------------------------------------
# Test 5: Kernel centering correctness
# ---------------------------------------------------------------------------

test_that("centered kernel has zero row and column means", {
    n <- 20
    set.seed(42)
    D <- matrix(abs(rnorm(n * n, mean = 100, sd = 50)), nrow = n, ncol = n)
    D <- (D + t(D)) / 2
    diag(D) <- 0

    Dmax <- max(D)
    K <- 1 - D / Dmax
    K[K < 0] <- 0

    K_c <- tcrdistR:::.center_kernel_matrix(K)

    expect_equal(rowMeans(K_c), rep(0, n), tolerance = 1e-12,
                 label = "centered kernel row means")
    expect_equal(colMeans(K_c), rep(0, n), tolerance = 1e-12,
                 label = "centered kernel column means")
    expect_equal(mean(K_c), 0, tolerance = 1e-14,
                 label = "centered kernel grand mean")
})


# ---------------------------------------------------------------------------
# Test 6: n_components > n reduces to n
# ---------------------------------------------------------------------------

test_that("requesting more components than TCRs returns at most n components", {
    dash_path <- test_path("fixtures", "dash.csv")
    skip_if_not(file.exists(dash_path), "dash.csv not found")

    tcrs <- .load_dash_100()
    skip_if(is.null(tcrs), "Could not load DASH data")

    result <- compute_tcrdist_kernel_pca(
        tcrs, "mouse",
        n_components = 500L,
        kernel = NULL
    )

    expect_true(result$n_components <= nrow(tcrs))
    expect_equal(nrow(result$embeddings), nrow(tcrs))
    expect_equal(ncol(result$embeddings), result$n_components)
    expect_true(all(result$eigenvalues > 0))
})


# ---------------------------------------------------------------------------
# Test 7: Small dataset works without error
# ---------------------------------------------------------------------------

test_that("small dataset (5 TCRs) works without error", {
    dash_path <- test_path("fixtures", "dash.csv")
    skip_if_not(file.exists(dash_path), "dash.csv not found")

    dash <- read.csv(dash_path, stringsAsFactors = FALSE, nrows = 5)
    tcrs <- data.frame(
        va    = dash$v_a_gene,
        cdr3a = dash$cdr3_a_aa,
        vb    = dash$v_b_gene,
        cdr3b = dash$cdr3_b_aa,
        stringsAsFactors = FALSE
    )

    result_default <- compute_tcrdist_kernel_pca(
        tcrs, "mouse", n_components = 10L, kernel = NULL
    )
    expect_true(result_default$n_components <= 5L)
    expect_equal(nrow(result_default$embeddings), 5L)
    expect_true(all(result_default$eigenvalues > 0))

    result_gaussian <- compute_tcrdist_kernel_pca(
        tcrs, "mouse", n_components = 10L, kernel = "gaussian"
    )
    expect_true(result_gaussian$n_components <= 5L)
    expect_equal(nrow(result_gaussian$embeddings), 5L)
    expect_true(all(result_gaussian$eigenvalues > 0))
})


# ---------------------------------------------------------------------------
# Test 8: RSpectra method matches eigen method
# ---------------------------------------------------------------------------

test_that("RSpectra method matches eigen method", {
    skip_if_not_installed("RSpectra")
    dash_path <- test_path("fixtures", "dash.csv")
    skip_if_not(file.exists(dash_path), "dash.csv not found")

    tcrs <- .load_dash_100()
    skip_if(is.null(tcrs), "Could not load DASH data")

    n_comp <- 20L

    result_eigen <- compute_tcrdist_kernel_pca(
        tcrs, "mouse", n_components = n_comp, method = "eigen"
    )
    result_rspectra <- compute_tcrdist_kernel_pca(
        tcrs, "mouse", n_components = n_comp, method = "RSpectra"
    )

    expect_equal(
        result_rspectra$eigenvalues[seq_len(n_comp)],
        result_eigen$eigenvalues[seq_len(n_comp)],
        tolerance = 1e-8,
        label = "RSpectra vs eigen eigenvalues"
    )

    for (k in seq_len(n_comp)) {
        r_col <- result_rspectra$embeddings[, k]
        e_col <- result_eigen$embeddings[, k]
        expect_equal(
            abs(r_col), abs(e_col), tolerance = 1e-6,
            info = sprintf("RSpectra vs eigen component %d (abs values)", k)
        )
    }
})


# ---------------------------------------------------------------------------
# Test 9: Auto method selects RSpectra when available
# ---------------------------------------------------------------------------

test_that("auto method selects RSpectra when available", {
    skip_if_not_installed("RSpectra")
    dash_path <- test_path("fixtures", "dash.csv")
    skip_if_not(file.exists(dash_path), "dash.csv not found")

    tcrs <- .load_dash_100()
    skip_if(is.null(tcrs), "Could not load DASH data")

    result_auto <- compute_tcrdist_kernel_pca(
        tcrs, "mouse", n_components = 20L, method = "auto"
    )
    result_rspectra <- compute_tcrdist_kernel_pca(
        tcrs, "mouse", n_components = 20L, method = "RSpectra"
    )

    expect_equal(result_auto$eigenvalues, result_rspectra$eigenvalues,
                 tolerance = 1e-14)
    expect_equal(result_auto$embeddings, result_rspectra$embeddings,
                 tolerance = 1e-14)

    # Negative case: requesting all components must fall back to eigen (ARPACK
    # cannot compute the full spectrum) and must not error.
    result_full <- compute_tcrdist_kernel_pca(
        tcrs, "mouse", n_components = nrow(tcrs), method = "auto"
    )
    result_eigen_full <- compute_tcrdist_kernel_pca(
        tcrs, "mouse", n_components = nrow(tcrs), method = "eigen"
    )
    expect_equal(result_full$eigenvalues, result_eigen_full$eigenvalues,
                 tolerance = 1e-14)
})


# ---------------------------------------------------------------------------
# Test 10: Input validation
# ---------------------------------------------------------------------------

test_that("compute_tcrdist_kernel_pca validates inputs", {
    bad_df <- data.frame(va = "x", stringsAsFactors = FALSE)
    expect_error(
        compute_tcrdist_kernel_pca(bad_df, "mouse"),
        "missing required columns"
    )

    df <- data.frame(
        va = "TRAV1*01", cdr3a = "CAVRD",
        vb = "TRBV1*01", cdr3b = "CASSI",
        stringsAsFactors = FALSE
    )
    expect_error(
        compute_tcrdist_kernel_pca(df, "mouse", kernel = "invalid"),
        "unrecognized kernel"
    )

    expect_error(
        compute_tcrdist_kernel_pca(df, "mouse", n_components = -1),
        "positive integer"
    )
})


# ---------------------------------------------------------------------------
# Test 11: Empty data.frame
# ---------------------------------------------------------------------------

test_that("empty data.frame returns empty result", {
    df <- data.frame(
        va = character(0), cdr3a = character(0),
        vb = character(0), cdr3b = character(0),
        stringsAsFactors = FALSE
    )

    result <- compute_tcrdist_kernel_pca(df, "mouse")
    expect_equal(result$n_components, 0L)
    expect_equal(nrow(result$embeddings), 0L)
    expect_equal(length(result$eigenvalues), 0L)
})


# ---------------------------------------------------------------------------
# Test 12: dist_matrix bypass
# ---------------------------------------------------------------------------

test_that("compute_tcrdist_kernel_pca accepts precomputed dist_matrix", {
    skip_on_cran()

    tcr_df <- data.frame(
        va = c("TRAV1-1*01", "TRAV1-2*01", "TRAV10*01",
               "TRAV1-1*01", "TRAV1-2*01"),
        cdr3a = c("CAVRDSSYKLIF", "CAVKDSSYKLIF", "CAVRDSYKLIF",
                   "CAVRDSSYKLIF", "CAVKDSYKLIF"),
        vb = c("TRBV5-1*01", "TRBV6-1*01", "TRBV7-2*01",
               "TRBV5-1*01", "TRBV6-1*01"),
        cdr3b = c("CASSIRSSYEQY", "CASSIKSSYEQY", "CASSIRSYEQY",
                   "CASSIRSSYEQF", "CASSIKSSYEQF"),
        stringsAsFactors = FALSE
    )

    dm <- tcrdist_matrix(tcr_df, "human")
    r1 <- compute_tcrdist_kernel_pca(tcr_df, "human", n_components = 3L)
    r2 <- compute_tcrdist_kernel_pca(dist_matrix = dm, n_components = 3L)
    expect_equal(r1$eigenvalues, r2$eigenvalues)
    expect_equal(nrow(r2$embeddings), 5L)
})


# ---------------------------------------------------------------------------
# Test 13: RSpectra path matches the scipy fixture (both kernels)
# ---------------------------------------------------------------------------

test_that("RSpectra path matches Python/scipy reference (both kernels)", {
    skip_if_not_installed("RSpectra")
    skip_if_not_installed("jsonlite")
    fixture_path <- test_path("fixtures", "kernel_pca_ref.json")
    skip_if_not(file.exists(fixture_path), "fixture not found")
    tcrs <- .load_dash_100()
    skip_if(is.null(tcrs), "Could not load DASH data")
    ref <- jsonlite::fromJSON(fixture_path, simplifyVector = TRUE)

    for (kern in list(list(kernel = NULL, ref = ref$default_kernel, sdev = 100),
                      list(kernel = "gaussian", ref = ref$gaussian_kernel,
                           sdev = ref$gaussian_kernel$sdev))) {
        res <- compute_tcrdist_kernel_pca(
            tcrs, ref$organism, n_components = ref$n_components,
            kernel = kern$kernel, gaussian_kernel_sdev = kern$sdev,
            method = "RSpectra"
        )
        py_eig <- kern$ref$eigenvalues
        expect_equal(res$eigenvalues[seq_along(py_eig)], py_eig,
                     tolerance = 1e-8)
        py_emb <- kern$ref$embeddings
        for (k in seq_len(ncol(py_emb))) {
            if (sd(py_emb[, k]) > 1e-12) {
                expect_true(abs(abs(cor(res$embeddings[, k], py_emb[, k])) - 1) < 1e-6)
            }
        }
    }
})


# ---------------------------------------------------------------------------
# Test 14: indefinite centered Gram - RSpectra returns same positives as eigen
# (regression guard for which = "LA"; "LM" would drop positive eigenvalues)
# ---------------------------------------------------------------------------

test_that("RSpectra matches eigen on an indefinite centered Gram", {
    skip_if_not_installed("RSpectra")
    dash_path <- test_path("fixtures", "dash.csv")
    skip_if_not(file.exists(dash_path), "dash.csv not found")

    dash <- read.csv(dash_path, stringsAsFactors = FALSE, nrows = 300)
    tcrs <- data.frame(vb = dash$v_b_gene, cdr3b = dash$cdr3_b_aa,
                       stringsAsFactors = FALSE)
    tcrs <- tcrs[!duplicated(tcrs), ]
    D <- tcrdist_matrix(tcrs, "mouse")
    # confirm the centered default-kernel Gram is genuinely indefinite
    gram <- 1 - D / max(D); gram[gram < 0] <- 0
    ev <- eigen(tcrdistR:::.center_kernel_matrix(gram), symmetric = TRUE,
                only.values = TRUE)$values
    skip_if(min(ev) >= -1e-6, "Gram not indefinite for this slice")

    k <- 50L
    re <- compute_tcrdist_kernel_pca(dist_matrix = D, n_components = k,
                                     method = "eigen")
    rr <- compute_tcrdist_kernel_pca(dist_matrix = D, n_components = k,
                                     method = "RSpectra")
    expect_equal(rr$n_components, re$n_components)
    expect_equal(rr$eigenvalues, re$eigenvalues, tolerance = 1e-8)
})


# ---------------------------------------------------------------------------
# Test 15: matrix-free operator equals dense-centered ARPACK
# ---------------------------------------------------------------------------

test_that("matrix-free ARPACK operator matches dense-centered ARPACK", {
    skip_if_not_installed("RSpectra")
    dash_path <- test_path("fixtures", "dash.csv")
    skip_if_not(file.exists(dash_path), "dash.csv not found")

    dash <- read.csv(dash_path, stringsAsFactors = FALSE, nrows = 200)
    tcrs <- data.frame(vb = dash$v_b_gene, cdr3b = dash$cdr3_b_aa,
                       stringsAsFactors = FALSE)
    tcrs <- tcrs[!duplicated(tcrs), ]
    D <- tcrdist_matrix(tcrs, "mouse")
    gram <- 1 - D / max(D); gram[gram < 0] <- 0

    ef <- tcrdistR:::.kpca_eigs_rspectra(gram, 30L, matrix_free = TRUE)
    ed <- tcrdistR:::.kpca_eigs_rspectra(gram, 30L, matrix_free = FALSE)
    expect_equal(sort(ef$values, decreasing = TRUE),
                 sort(ed$values, decreasing = TRUE), tolerance = 1e-10)
})


# ---------------------------------------------------------------------------
# Test 16: scale - RSpectra and eigen agree at n = 1500
# ---------------------------------------------------------------------------

test_that("RSpectra and eigen agree at n = 1500", {
    skip_on_cran()
    skip_if_not_installed("RSpectra")
    dash_path <- test_path("fixtures", "dash.csv")
    skip_if_not(file.exists(dash_path), "dash.csv not found")

    dash <- read.csv(dash_path, stringsAsFactors = FALSE)
    skip_if(nrow(dash) < 1500, "need >= 1500 DASH rows")
    tcrs <- data.frame(va = dash$v_a_gene, cdr3a = dash$cdr3_a_aa,
                       vb = dash$v_b_gene, cdr3b = dash$cdr3_b_aa,
                       stringsAsFactors = FALSE)
    tcrs <- tcrs[!duplicated(tcrs), ][seq_len(1500), ]
    D <- tcrdist_matrix(tcrs, "mouse")

    re <- compute_tcrdist_kernel_pca(dist_matrix = D, n_components = 50L,
                                     method = "eigen")
    rr <- compute_tcrdist_kernel_pca(dist_matrix = D, n_components = 50L,
                                     method = "RSpectra")
    expect_equal(rr$eigenvalues[seq_len(50L)], re$eigenvalues[seq_len(50L)],
                 tolerance = 1e-8)
})
