// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_build_bsd4
NumericMatrix rcpp_build_bsd4();
RcppExport SEXP _tcrdistR_rcpp_build_bsd4() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_build_bsd4());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_blosum62_lookup
int rcpp_blosum62_lookup(const std::string& aa1, const std::string& aa2);
RcppExport SEXP _tcrdistR_rcpp_blosum62_lookup(SEXP aa1SEXP, SEXP aa2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type aa1(aa1SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type aa2(aa2SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_blosum62_lookup(aa1, aa2));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_weighted_cdr3_distance
double rcpp_weighted_cdr3_distance(const std::string& seq1, const std::string& seq2, int weight_cdr3_region, int gap_penalty_cdr3_region);
RcppExport SEXP _tcrdistR_rcpp_weighted_cdr3_distance(SEXP seq1SEXP, SEXP seq2SEXP, SEXP weight_cdr3_regionSEXP, SEXP gap_penalty_cdr3_regionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type seq1(seq1SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type seq2(seq2SEXP);
    Rcpp::traits::input_parameter< int >::type weight_cdr3_region(weight_cdr3_regionSEXP);
    Rcpp::traits::input_parameter< int >::type gap_penalty_cdr3_region(gap_penalty_cdr3_regionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_weighted_cdr3_distance(seq1, seq2, weight_cdr3_region, gap_penalty_cdr3_region));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_blosum_sequence_distance
double rcpp_blosum_sequence_distance(const std::string& seq1, const std::string& seq2, double gap_penalty);
RcppExport SEXP _tcrdistR_rcpp_blosum_sequence_distance(SEXP seq1SEXP, SEXP seq2SEXP, SEXP gap_penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type seq1(seq1SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type seq2(seq2SEXP);
    Rcpp::traits::input_parameter< double >::type gap_penalty(gap_penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_blosum_sequence_distance(seq1, seq2, gap_penalty));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_tcrdist_matrix
NumericMatrix rcpp_tcrdist_matrix(const CharacterVector& va_genes, const CharacterVector& cdr3a_seqs, const CharacterVector& vb_genes, const CharacterVector& cdr3b_seqs, const NumericMatrix& v_dist_a, const NumericMatrix& v_dist_b, int weight_cdr3_region, int gap_penalty_cdr3_region);
RcppExport SEXP _tcrdistR_rcpp_tcrdist_matrix(SEXP va_genesSEXP, SEXP cdr3a_seqsSEXP, SEXP vb_genesSEXP, SEXP cdr3b_seqsSEXP, SEXP v_dist_aSEXP, SEXP v_dist_bSEXP, SEXP weight_cdr3_regionSEXP, SEXP gap_penalty_cdr3_regionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type va_genes(va_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type cdr3a_seqs(cdr3a_seqsSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type vb_genes(vb_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type cdr3b_seqs(cdr3b_seqsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type v_dist_a(v_dist_aSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type v_dist_b(v_dist_bSEXP);
    Rcpp::traits::input_parameter< int >::type weight_cdr3_region(weight_cdr3_regionSEXP);
    Rcpp::traits::input_parameter< int >::type gap_penalty_cdr3_region(gap_penalty_cdr3_regionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_tcrdist_matrix(va_genes, cdr3a_seqs, vb_genes, cdr3b_seqs, v_dist_a, v_dist_b, weight_cdr3_region, gap_penalty_cdr3_region));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_compute_v_region_distances
NumericMatrix rcpp_compute_v_region_distances(const CharacterVector& gene_ids, const CharacterVector& loop_seqs, double weight_v_region, double gap_penalty_v_region);
RcppExport SEXP _tcrdistR_rcpp_compute_v_region_distances(SEXP gene_idsSEXP, SEXP loop_seqsSEXP, SEXP weight_v_regionSEXP, SEXP gap_penalty_v_regionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type gene_ids(gene_idsSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type loop_seqs(loop_seqsSEXP);
    Rcpp::traits::input_parameter< double >::type weight_v_region(weight_v_regionSEXP);
    Rcpp::traits::input_parameter< double >::type gap_penalty_v_region(gap_penalty_v_regionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_compute_v_region_distances(gene_ids, loop_seqs, weight_v_region, gap_penalty_v_region));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tcrdistR_rcpp_build_bsd4", (DL_FUNC) &_tcrdistR_rcpp_build_bsd4, 0},
    {"_tcrdistR_rcpp_blosum62_lookup", (DL_FUNC) &_tcrdistR_rcpp_blosum62_lookup, 2},
    {"_tcrdistR_rcpp_weighted_cdr3_distance", (DL_FUNC) &_tcrdistR_rcpp_weighted_cdr3_distance, 4},
    {"_tcrdistR_rcpp_blosum_sequence_distance", (DL_FUNC) &_tcrdistR_rcpp_blosum_sequence_distance, 3},
    {"_tcrdistR_rcpp_tcrdist_matrix", (DL_FUNC) &_tcrdistR_rcpp_tcrdist_matrix, 8},
    {"_tcrdistR_rcpp_compute_v_region_distances", (DL_FUNC) &_tcrdistR_rcpp_compute_v_region_distances, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_tcrdistR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
