// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_build_bsd4
NumericMatrix rcpp_build_bsd4();
RcppExport SEXP _tcrdistR_rcpp_build_bsd4() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_build_bsd4());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_blosum62_lookup
int rcpp_blosum62_lookup(const std::string& aa1, const std::string& aa2);
RcppExport SEXP _tcrdistR_rcpp_blosum62_lookup(SEXP aa1SEXP, SEXP aa2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type aa1(aa1SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type aa2(aa2SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_blosum62_lookup(aa1, aa2));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_knn_from_distance_matrix
Rcpp::List rcpp_knn_from_distance_matrix(const NumericMatrix& D, int K, const IntegerVector& agroups, const IntegerVector& bgroups, bool sort_nbrs);
RcppExport SEXP _tcrdistR_rcpp_knn_from_distance_matrix(SEXP DSEXP, SEXP KSEXP, SEXP agroupsSEXP, SEXP bgroupsSEXP, SEXP sort_nbrsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type agroups(agroupsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type bgroups(bgroupsSEXP);
    Rcpp::traits::input_parameter< bool >::type sort_nbrs(sort_nbrsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_knn_from_distance_matrix(D, K, agroups, bgroups, sort_nbrs));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_knn_from_pca_matrix
Rcpp::List rcpp_knn_from_pca_matrix(const NumericMatrix& pca_matrix, int K, const IntegerVector& agroups, const IntegerVector& bgroups, bool sort_nbrs);
RcppExport SEXP _tcrdistR_rcpp_knn_from_pca_matrix(SEXP pca_matrixSEXP, SEXP KSEXP, SEXP agroupsSEXP, SEXP bgroupsSEXP, SEXP sort_nbrsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type pca_matrix(pca_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type agroups(agroupsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type bgroups(bgroupsSEXP);
    Rcpp::traits::input_parameter< bool >::type sort_nbrs(sort_nbrsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_knn_from_pca_matrix(pca_matrix, K, agroups, bgroups, sort_nbrs));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_poisson_test_loop
Rcpp::List rcpp_poisson_test_loop(const Rcpp::List& all_nbr_indices, const Rcpp::List& all_nbr_distances, const Rcpp::NumericMatrix& bg_freqs, const Rcpp::IntegerVector& agroups, const Rcpp::IntegerVector& bgroups, const Rcpp::IntegerVector& radii, double n_bg_pairs, double pvalue_threshold, int num_clones, Rcpp::Nullable<Rcpp::IntegerVector> clusters_gex_nullable, bool use_conservative_pvalues);
RcppExport SEXP _tcrdistR_rcpp_poisson_test_loop(SEXP all_nbr_indicesSEXP, SEXP all_nbr_distancesSEXP, SEXP bg_freqsSEXP, SEXP agroupsSEXP, SEXP bgroupsSEXP, SEXP radiiSEXP, SEXP n_bg_pairsSEXP, SEXP pvalue_thresholdSEXP, SEXP num_clonesSEXP, SEXP clusters_gex_nullableSEXP, SEXP use_conservative_pvaluesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type all_nbr_indices(all_nbr_indicesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type all_nbr_distances(all_nbr_distancesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type bg_freqs(bg_freqsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type agroups(agroupsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type bgroups(bgroupsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type radii(radiiSEXP);
    Rcpp::traits::input_parameter< double >::type n_bg_pairs(n_bg_pairsSEXP);
    Rcpp::traits::input_parameter< double >::type pvalue_threshold(pvalue_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type num_clones(num_clonesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type clusters_gex_nullable(clusters_gex_nullableSEXP);
    Rcpp::traits::input_parameter< bool >::type use_conservative_pvalues(use_conservative_pvaluesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_poisson_test_loop(all_nbr_indices, all_nbr_distances, bg_freqs, agroups, bgroups, radii, n_bg_pairs, pvalue_threshold, num_clones, clusters_gex_nullable, use_conservative_pvalues));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_count_nuc_matches
int rcpp_count_nuc_matches(const std::string& a, const std::string& b, int mismatch_score);
RcppExport SEXP _tcrdistR_rcpp_count_nuc_matches(SEXP aSEXP, SEXP bSEXP, SEXP mismatch_scoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type mismatch_score(mismatch_scoreSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_count_nuc_matches(a, b, mismatch_score));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_find_alternate_alleles_batch
Rcpp::List rcpp_find_alternate_alleles_batch(const CharacterVector& va_genes, const CharacterVector& ja_genes, const CharacterVector& cdr3a_nucseqs, const CharacterVector& vb_genes, const CharacterVector& jb_genes, const CharacterVector& cdr3b_nucseqs, const CharacterVector& all_gene_names, const CharacterVector& all_v_cdr3_nucseqs, const CharacterVector& all_j_cdr3_nucseqs, int mismatch_score, int min_improvement);
RcppExport SEXP _tcrdistR_rcpp_find_alternate_alleles_batch(SEXP va_genesSEXP, SEXP ja_genesSEXP, SEXP cdr3a_nucseqsSEXP, SEXP vb_genesSEXP, SEXP jb_genesSEXP, SEXP cdr3b_nucseqsSEXP, SEXP all_gene_namesSEXP, SEXP all_v_cdr3_nucseqsSEXP, SEXP all_j_cdr3_nucseqsSEXP, SEXP mismatch_scoreSEXP, SEXP min_improvementSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type va_genes(va_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type ja_genes(ja_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type cdr3a_nucseqs(cdr3a_nucseqsSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type vb_genes(vb_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type jb_genes(jb_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type cdr3b_nucseqs(cdr3b_nucseqsSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type all_gene_names(all_gene_namesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type all_v_cdr3_nucseqs(all_v_cdr3_nucseqsSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type all_j_cdr3_nucseqs(all_j_cdr3_nucseqsSEXP);
    Rcpp::traits::input_parameter< int >::type mismatch_score(mismatch_scoreSEXP);
    Rcpp::traits::input_parameter< int >::type min_improvement(min_improvementSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_find_alternate_alleles_batch(va_genes, ja_genes, cdr3a_nucseqs, vb_genes, jb_genes, cdr3b_nucseqs, all_gene_names, all_v_cdr3_nucseqs, all_j_cdr3_nucseqs, mismatch_score, min_improvement));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_resample_shuffled_tcr_chains
Rcpp::DataFrame rcpp_resample_shuffled_tcr_chains(const CharacterVector& junction_v_genes, const CharacterVector& junction_j_genes, const CharacterVector& junction_nucseqs, const Rcpp::List& junction_breakpoints_pre_d, const Rcpp::List& junction_breakpoints_post_d, const std::string& chain, int num_samples, int max_attempts);
RcppExport SEXP _tcrdistR_rcpp_resample_shuffled_tcr_chains(SEXP junction_v_genesSEXP, SEXP junction_j_genesSEXP, SEXP junction_nucseqsSEXP, SEXP junction_breakpoints_pre_dSEXP, SEXP junction_breakpoints_post_dSEXP, SEXP chainSEXP, SEXP num_samplesSEXP, SEXP max_attemptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type junction_v_genes(junction_v_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type junction_j_genes(junction_j_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type junction_nucseqs(junction_nucseqsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type junction_breakpoints_pre_d(junction_breakpoints_pre_dSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type junction_breakpoints_post_d(junction_breakpoints_post_dSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type chain(chainSEXP);
    Rcpp::traits::input_parameter< int >::type num_samples(num_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type max_attempts(max_attemptsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_resample_shuffled_tcr_chains(junction_v_genes, junction_j_genes, junction_nucseqs, junction_breakpoints_pre_d, junction_breakpoints_post_d, chain, num_samples, max_attempts));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_calc_background_distributions
Rcpp::NumericMatrix rcpp_calc_background_distributions(const Rcpp::CharacterVector& fg_va, const Rcpp::CharacterVector& fg_cdr3a, const Rcpp::CharacterVector& fg_vb, const Rcpp::CharacterVector& fg_cdr3b, const Rcpp::CharacterVector& bg_va, const Rcpp::CharacterVector& bg_cdr3a, const Rcpp::CharacterVector& bg_vb, const Rcpp::CharacterVector& bg_cdr3b, const Rcpp::NumericMatrix& v_dist_a, const Rcpp::NumericMatrix& v_dist_b, int max_dist, double pseudocount, int weight_cdr3_region, int gap_penalty_cdr3_region);
RcppExport SEXP _tcrdistR_rcpp_calc_background_distributions(SEXP fg_vaSEXP, SEXP fg_cdr3aSEXP, SEXP fg_vbSEXP, SEXP fg_cdr3bSEXP, SEXP bg_vaSEXP, SEXP bg_cdr3aSEXP, SEXP bg_vbSEXP, SEXP bg_cdr3bSEXP, SEXP v_dist_aSEXP, SEXP v_dist_bSEXP, SEXP max_distSEXP, SEXP pseudocountSEXP, SEXP weight_cdr3_regionSEXP, SEXP gap_penalty_cdr3_regionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type fg_va(fg_vaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type fg_cdr3a(fg_cdr3aSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type fg_vb(fg_vbSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type fg_cdr3b(fg_cdr3bSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type bg_va(bg_vaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type bg_cdr3a(bg_cdr3aSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type bg_vb(bg_vbSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type bg_cdr3b(bg_cdr3bSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type v_dist_a(v_dist_aSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type v_dist_b(v_dist_bSEXP);
    Rcpp::traits::input_parameter< int >::type max_dist(max_distSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    Rcpp::traits::input_parameter< int >::type weight_cdr3_region(weight_cdr3_regionSEXP);
    Rcpp::traits::input_parameter< int >::type gap_penalty_cdr3_region(gap_penalty_cdr3_regionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_calc_background_distributions(fg_va, fg_cdr3a, fg_vb, fg_cdr3b, bg_va, bg_cdr3a, bg_vb, bg_cdr3b, v_dist_a, v_dist_b, max_dist, pseudocount, weight_cdr3_region, gap_penalty_cdr3_region));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_weighted_cdr3_distance
double rcpp_weighted_cdr3_distance(const std::string& seq1, const std::string& seq2, int weight_cdr3_region, int gap_penalty_cdr3_region);
RcppExport SEXP _tcrdistR_rcpp_weighted_cdr3_distance(SEXP seq1SEXP, SEXP seq2SEXP, SEXP weight_cdr3_regionSEXP, SEXP gap_penalty_cdr3_regionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type seq1(seq1SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type seq2(seq2SEXP);
    Rcpp::traits::input_parameter< int >::type weight_cdr3_region(weight_cdr3_regionSEXP);
    Rcpp::traits::input_parameter< int >::type gap_penalty_cdr3_region(gap_penalty_cdr3_regionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_weighted_cdr3_distance(seq1, seq2, weight_cdr3_region, gap_penalty_cdr3_region));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_blosum_sequence_distance
double rcpp_blosum_sequence_distance(const std::string& seq1, const std::string& seq2, double gap_penalty);
RcppExport SEXP _tcrdistR_rcpp_blosum_sequence_distance(SEXP seq1SEXP, SEXP seq2SEXP, SEXP gap_penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type seq1(seq1SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type seq2(seq2SEXP);
    Rcpp::traits::input_parameter< double >::type gap_penalty(gap_penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_blosum_sequence_distance(seq1, seq2, gap_penalty));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_tcrdist_knn
Rcpp::List rcpp_tcrdist_knn(const CharacterVector& va_genes, const CharacterVector& cdr3a_seqs, const CharacterVector& vb_genes, const CharacterVector& cdr3b_seqs, const NumericMatrix& v_dist_a, const NumericMatrix& v_dist_b, int K, const IntegerVector& agroups, const IntegerVector& bgroups, bool sort_nbrs, int weight_cdr3_region, int gap_penalty_cdr3_region);
RcppExport SEXP _tcrdistR_rcpp_tcrdist_knn(SEXP va_genesSEXP, SEXP cdr3a_seqsSEXP, SEXP vb_genesSEXP, SEXP cdr3b_seqsSEXP, SEXP v_dist_aSEXP, SEXP v_dist_bSEXP, SEXP KSEXP, SEXP agroupsSEXP, SEXP bgroupsSEXP, SEXP sort_nbrsSEXP, SEXP weight_cdr3_regionSEXP, SEXP gap_penalty_cdr3_regionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type va_genes(va_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type cdr3a_seqs(cdr3a_seqsSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type vb_genes(vb_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type cdr3b_seqs(cdr3b_seqsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type v_dist_a(v_dist_aSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type v_dist_b(v_dist_bSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type agroups(agroupsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type bgroups(bgroupsSEXP);
    Rcpp::traits::input_parameter< bool >::type sort_nbrs(sort_nbrsSEXP);
    Rcpp::traits::input_parameter< int >::type weight_cdr3_region(weight_cdr3_regionSEXP);
    Rcpp::traits::input_parameter< int >::type gap_penalty_cdr3_region(gap_penalty_cdr3_regionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_tcrdist_knn(va_genes, cdr3a_seqs, vb_genes, cdr3b_seqs, v_dist_a, v_dist_b, K, agroups, bgroups, sort_nbrs, weight_cdr3_region, gap_penalty_cdr3_region));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_tcrdist_matrix
NumericMatrix rcpp_tcrdist_matrix(const CharacterVector& va_genes, const CharacterVector& cdr3a_seqs, const CharacterVector& vb_genes, const CharacterVector& cdr3b_seqs, const NumericMatrix& v_dist_a, const NumericMatrix& v_dist_b, int weight_cdr3_region, int gap_penalty_cdr3_region);
RcppExport SEXP _tcrdistR_rcpp_tcrdist_matrix(SEXP va_genesSEXP, SEXP cdr3a_seqsSEXP, SEXP vb_genesSEXP, SEXP cdr3b_seqsSEXP, SEXP v_dist_aSEXP, SEXP v_dist_bSEXP, SEXP weight_cdr3_regionSEXP, SEXP gap_penalty_cdr3_regionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type va_genes(va_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type cdr3a_seqs(cdr3a_seqsSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type vb_genes(vb_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type cdr3b_seqs(cdr3b_seqsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type v_dist_a(v_dist_aSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type v_dist_b(v_dist_bSEXP);
    Rcpp::traits::input_parameter< int >::type weight_cdr3_region(weight_cdr3_regionSEXP);
    Rcpp::traits::input_parameter< int >::type gap_penalty_cdr3_region(gap_penalty_cdr3_regionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_tcrdist_matrix(va_genes, cdr3a_seqs, vb_genes, cdr3b_seqs, v_dist_a, v_dist_b, weight_cdr3_region, gap_penalty_cdr3_region));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_tcrdist_radius_neighbors
Rcpp::List rcpp_tcrdist_radius_neighbors(const CharacterVector& va_genes, const CharacterVector& cdr3a_seqs, const CharacterVector& vb_genes, const CharacterVector& cdr3b_seqs, const NumericMatrix& v_dist_a, const NumericMatrix& v_dist_b, double radius, const IntegerVector& agroups, const IntegerVector& bgroups, int weight_cdr3_region, int gap_penalty_cdr3_region);
RcppExport SEXP _tcrdistR_rcpp_tcrdist_radius_neighbors(SEXP va_genesSEXP, SEXP cdr3a_seqsSEXP, SEXP vb_genesSEXP, SEXP cdr3b_seqsSEXP, SEXP v_dist_aSEXP, SEXP v_dist_bSEXP, SEXP radiusSEXP, SEXP agroupsSEXP, SEXP bgroupsSEXP, SEXP weight_cdr3_regionSEXP, SEXP gap_penalty_cdr3_regionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type va_genes(va_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type cdr3a_seqs(cdr3a_seqsSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type vb_genes(vb_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type cdr3b_seqs(cdr3b_seqsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type v_dist_a(v_dist_aSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type v_dist_b(v_dist_bSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type agroups(agroupsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type bgroups(bgroupsSEXP);
    Rcpp::traits::input_parameter< int >::type weight_cdr3_region(weight_cdr3_regionSEXP);
    Rcpp::traits::input_parameter< int >::type gap_penalty_cdr3_region(gap_penalty_cdr3_regionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_tcrdist_radius_neighbors(va_genes, cdr3a_seqs, vb_genes, cdr3b_seqs, v_dist_a, v_dist_b, radius, agroups, bgroups, weight_cdr3_region, gap_penalty_cdr3_region));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_tcrdist_rect
NumericMatrix rcpp_tcrdist_rect(const CharacterVector& query_va, const CharacterVector& query_cdr3a, const CharacterVector& query_vb, const CharacterVector& query_cdr3b, const CharacterVector& ref_va, const CharacterVector& ref_cdr3a, const CharacterVector& ref_vb, const CharacterVector& ref_cdr3b, const NumericMatrix& v_dist_a, const NumericMatrix& v_dist_b, int weight_cdr3_region, int gap_penalty_cdr3_region);
RcppExport SEXP _tcrdistR_rcpp_tcrdist_rect(SEXP query_vaSEXP, SEXP query_cdr3aSEXP, SEXP query_vbSEXP, SEXP query_cdr3bSEXP, SEXP ref_vaSEXP, SEXP ref_cdr3aSEXP, SEXP ref_vbSEXP, SEXP ref_cdr3bSEXP, SEXP v_dist_aSEXP, SEXP v_dist_bSEXP, SEXP weight_cdr3_regionSEXP, SEXP gap_penalty_cdr3_regionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type query_va(query_vaSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type query_cdr3a(query_cdr3aSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type query_vb(query_vbSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type query_cdr3b(query_cdr3bSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type ref_va(ref_vaSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type ref_cdr3a(ref_cdr3aSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type ref_vb(ref_vbSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type ref_cdr3b(ref_cdr3bSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type v_dist_a(v_dist_aSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type v_dist_b(v_dist_bSEXP);
    Rcpp::traits::input_parameter< int >::type weight_cdr3_region(weight_cdr3_regionSEXP);
    Rcpp::traits::input_parameter< int >::type gap_penalty_cdr3_region(gap_penalty_cdr3_regionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_tcrdist_rect(query_va, query_cdr3a, query_vb, query_cdr3b, ref_va, ref_cdr3a, ref_vb, ref_cdr3b, v_dist_a, v_dist_b, weight_cdr3_region, gap_penalty_cdr3_region));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_tcrdist_sparse
Rcpp::List rcpp_tcrdist_sparse(const CharacterVector& va_genes, const CharacterVector& cdr3a_seqs, const CharacterVector& vb_genes, const CharacterVector& cdr3b_seqs, const NumericMatrix& v_dist_a, const NumericMatrix& v_dist_b, double threshold, int weight_cdr3_region, int gap_penalty_cdr3_region);
RcppExport SEXP _tcrdistR_rcpp_tcrdist_sparse(SEXP va_genesSEXP, SEXP cdr3a_seqsSEXP, SEXP vb_genesSEXP, SEXP cdr3b_seqsSEXP, SEXP v_dist_aSEXP, SEXP v_dist_bSEXP, SEXP thresholdSEXP, SEXP weight_cdr3_regionSEXP, SEXP gap_penalty_cdr3_regionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type va_genes(va_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type cdr3a_seqs(cdr3a_seqsSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type vb_genes(vb_genesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type cdr3b_seqs(cdr3b_seqsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type v_dist_a(v_dist_aSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type v_dist_b(v_dist_bSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type weight_cdr3_region(weight_cdr3_regionSEXP);
    Rcpp::traits::input_parameter< int >::type gap_penalty_cdr3_region(gap_penalty_cdr3_regionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_tcrdist_sparse(va_genes, cdr3a_seqs, vb_genes, cdr3b_seqs, v_dist_a, v_dist_b, threshold, weight_cdr3_region, gap_penalty_cdr3_region));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_compute_v_region_distances
NumericMatrix rcpp_compute_v_region_distances(const CharacterVector& gene_ids, const CharacterVector& loop_seqs, double weight_v_region, double gap_penalty_v_region);
RcppExport SEXP _tcrdistR_rcpp_compute_v_region_distances(SEXP gene_idsSEXP, SEXP loop_seqsSEXP, SEXP weight_v_regionSEXP, SEXP gap_penalty_v_regionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type gene_ids(gene_idsSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type loop_seqs(loop_seqsSEXP);
    Rcpp::traits::input_parameter< double >::type weight_v_region(weight_v_regionSEXP);
    Rcpp::traits::input_parameter< double >::type gap_penalty_v_region(gap_penalty_v_regionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_compute_v_region_distances(gene_ids, loop_seqs, weight_v_region, gap_penalty_v_region));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tcrdistR_rcpp_build_bsd4", (DL_FUNC) &_tcrdistR_rcpp_build_bsd4, 0},
    {"_tcrdistR_rcpp_blosum62_lookup", (DL_FUNC) &_tcrdistR_rcpp_blosum62_lookup, 2},
    {"_tcrdistR_rcpp_knn_from_distance_matrix", (DL_FUNC) &_tcrdistR_rcpp_knn_from_distance_matrix, 5},
    {"_tcrdistR_rcpp_knn_from_pca_matrix", (DL_FUNC) &_tcrdistR_rcpp_knn_from_pca_matrix, 5},
    {"_tcrdistR_rcpp_poisson_test_loop", (DL_FUNC) &_tcrdistR_rcpp_poisson_test_loop, 11},
    {"_tcrdistR_rcpp_count_nuc_matches", (DL_FUNC) &_tcrdistR_rcpp_count_nuc_matches, 3},
    {"_tcrdistR_rcpp_find_alternate_alleles_batch", (DL_FUNC) &_tcrdistR_rcpp_find_alternate_alleles_batch, 11},
    {"_tcrdistR_rcpp_resample_shuffled_tcr_chains", (DL_FUNC) &_tcrdistR_rcpp_resample_shuffled_tcr_chains, 8},
    {"_tcrdistR_rcpp_calc_background_distributions", (DL_FUNC) &_tcrdistR_rcpp_calc_background_distributions, 14},
    {"_tcrdistR_rcpp_weighted_cdr3_distance", (DL_FUNC) &_tcrdistR_rcpp_weighted_cdr3_distance, 4},
    {"_tcrdistR_rcpp_blosum_sequence_distance", (DL_FUNC) &_tcrdistR_rcpp_blosum_sequence_distance, 3},
    {"_tcrdistR_rcpp_tcrdist_knn", (DL_FUNC) &_tcrdistR_rcpp_tcrdist_knn, 12},
    {"_tcrdistR_rcpp_tcrdist_matrix", (DL_FUNC) &_tcrdistR_rcpp_tcrdist_matrix, 8},
    {"_tcrdistR_rcpp_tcrdist_radius_neighbors", (DL_FUNC) &_tcrdistR_rcpp_tcrdist_radius_neighbors, 11},
    {"_tcrdistR_rcpp_tcrdist_rect", (DL_FUNC) &_tcrdistR_rcpp_tcrdist_rect, 12},
    {"_tcrdistR_rcpp_tcrdist_sparse", (DL_FUNC) &_tcrdistR_rcpp_tcrdist_sparse, 9},
    {"_tcrdistR_rcpp_compute_v_region_distances", (DL_FUNC) &_tcrdistR_rcpp_compute_v_region_distances, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_tcrdistR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
