# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build the BSD4 amino acid distance matrix (C++ constexpr values)
#'
#' Returns the 20x20 BSD4 distance matrix derived from BLOSUM62 using the
#' CoNGA transformation:
#' \itemize{
#'   \item diagonal (a == b): 0
#'   \item off-diagonal, BLOSUM62 < 0: 4
#'   \item off-diagonal, BLOSUM62 >= 0: 4 - BLOSUM62
#' }
#' Row and column names follow alphabetical single-letter amino acid order
#' (A C D E F G H I K L M N P Q R S T V W Y), matching \code{AMINO_ACIDS}
#' in rconga.
#'
#' The values are compiled into the package as \code{constexpr} C++ arrays;
#' this function exposes them to R for verification and for use by any R
#' code that needs the matrix.
#'
#' @return A named 20x20 \code{NumericMatrix} of BSD4 distances.
#' @examples
#' \dontrun{
#'   bsd4 <- rcpp_build_bsd4()
#'   bsd4["A", "S"]  # 3 (BLOSUM62[A,S]=1, BSD4=4-1=3)
#'   bsd4["A", "A"]  # 0 (diagonal)
#'   bsd4["A", "C"]  # 4 (BLOSUM62=-something negative)
#' }
#' @export
rcpp_build_bsd4 <- function() {
    .Call(`_tcrdistR_rcpp_build_bsd4`)
}

#' Look up a single BLOSUM62 score for two amino acids
#'
#' @param aa1 Single-letter amino acid code (length-1 character string).
#' @param aa2 Single-letter amino acid code (length-1 character string).
#' @return Integer BLOSUM62 score for the pair.
#' @keywords internal
rcpp_blosum62_lookup <- function(aa1, aa2) {
    .Call(`_tcrdistR_rcpp_blosum62_lookup`, aa1, aa2)
}

#' Weighted CDR3 distance (C++ implementation)
#'
#' Direct C++ port of the CDR3 distance algorithm from
#' \code{rconga/src/tcrdist_rcpp.cpp}.  Uses hard-coded \code{ntrim = 3},
#' \code{ctrim = 2} (\code{TRIM_CDR3S = TRUE}) and the fixed gap position
#' formula \code{min(6, 3 + (lenshort - 5) %/% 2)} (\code{ALIGN_CDR3S =
#' FALSE}).
#'
#' BSD4 values are compiled in as \code{constexpr} (no matrix argument
#' needed).  The result is numerically identical to
#' \code{rconga::rcpp_weighted_cdr3_distance()} for valid inputs.
#'
#' @param seq1 Character string. First CDR3 amino acid sequence.
#' @param seq2 Character string. Second CDR3 amino acid sequence.
#' @param weight_cdr3_region Integer. Multiplied by the raw alignment distance.
#'   Default 3 matches \code{WEIGHT_CDR3_REGION}.
#' @param gap_penalty_cdr3_region Integer. Per-residue length-difference penalty.
#'   Default 12 matches \code{GAP_PENALTY_CDR3_REGION}.
#' @return Numeric scalar: the weighted CDR3 distance.
#' @examples
#' \dontrun{
#'   rcpp_weighted_cdr3_distance("CASSIRSSYEQYF", "CASSIRSYEQYF")
#' }
#' @export
rcpp_weighted_cdr3_distance <- function(seq1, seq2, weight_cdr3_region = 3L, gap_penalty_cdr3_region = 12L) {
    .Call(`_tcrdistR_rcpp_weighted_cdr3_distance`, seq1, seq2, weight_cdr3_region, gap_penalty_cdr3_region)
}

#' Aligned sequence distance using BSD4 substitution costs (C++ implementation)
#'
#' Computes the total BSD4 distance between two pre-aligned amino acid strings
#' of equal length.  Matches \code{blosum_sequence_distance()} in
#' \code{rconga/R/tcr_distances.R} exactly.
#'
#' Position handling:
#' \itemize{
#'   \item Both characters are \code{" "} (space): position skipped (padding).
#'     The function stops with an error if only one character is a space.
#'   \item Both characters are \code{"."} (gap): distance 0.
#'   \item Both characters are \code{"*"} (stop codon): distance 0.
#'   \item One character is \code{"."} or \code{"*"}: \code{gap_penalty}.
#'   \item Both are valid amino acids: BSD4 lookup from the constexpr table.
#' }
#'
#' @param seq1 Character string. Aligned sequence (may contain \code{" "},
#'   \code{"."}, or \code{"*"}).
#' @param seq2 Character string. Aligned sequence of the same length as
#'   \code{seq1}.
#' @param gap_penalty Numeric. Applied when exactly one position is a gap or
#'   stop-codon character. Default 4.0 matches \code{GAP_PENALTY_V_REGION}.
#' @return Numeric scalar: sum of per-position BSD4 distances.
#' @examples
#' \dontrun{
#'   rcpp_blosum_sequence_distance("ACDE", "ACDF")
#' }
#' @export
rcpp_blosum_sequence_distance <- function(seq1, seq2, gap_penalty = 4.0) {
    .Call(`_tcrdistR_rcpp_blosum_sequence_distance`, seq1, seq2, gap_penalty)
}

#' Pairwise TCRdist matrix (C++ implementation)
#'
#' Computes the full N x N symmetric matrix of paired-chain TCRdist distances.
#' For each pair \code{(i, j)}:
#' \deqn{
#'   d(i,j) = v\_dist\_a[va_i, va_j] + cdr3\_dist(cdr3a_i, cdr3a_j)
#'           + v\_dist\_b[vb_i, vb_j] + cdr3\_dist(cdr3b_i, cdr3b_j)
#' }
#'
#' Only the upper triangle is computed; it is mirrored to the lower triangle.
#' The diagonal is zero.  \code{Rcpp::checkUserInterrupt()} is called every
#' 100 outer-loop rows to allow the user to interrupt long computations.
#'
#' BSD4 values are compiled in as \code{constexpr}; no \code{bsd4} matrix
#' argument is needed (unlike the rconga equivalent).
#'
#' @param va_genes   Character vector of length N. Alpha V-gene allele names.
#' @param cdr3a_seqs Character vector of length N. Alpha CDR3 sequences.
#' @param vb_genes   Character vector of length N. Beta V-gene allele names.
#' @param cdr3b_seqs Character vector of length N. Beta CDR3 sequences.
#' @param v_dist_a   Named square \code{NumericMatrix}. Pre-computed pairwise
#'   V-region distances for alpha genes (row/column names are V-gene allele
#'   strings, e.g. \code{"TRAV1-1*01"}).
#' @param v_dist_b   Named square \code{NumericMatrix}. Same structure for
#'   beta genes.
#' @param weight_cdr3_region Integer. CDR3 alignment distance multiplier.
#'   Default 3 matches \code{WEIGHT_CDR3_REGION}.
#' @param gap_penalty_cdr3_region Integer. Per-residue length-difference
#'   penalty.  Default 12 matches \code{GAP_PENALTY_CDR3_REGION}.
#' @return An N x N symmetric \code{NumericMatrix} of TCRdist distances.
#' @examples
#' \dontrun{
#'   mat <- rcpp_tcrdist_matrix(
#'     va_genes = c("TRAV1-1*01", "TRAV1-2*01"),
#'     cdr3a_seqs = c("CAVSANSGTYF", "CAVSANSGTYF"),
#'     vb_genes = c("TRBV20-1*01", "TRBV20-1*01"),
#'     cdr3b_seqs = c("CASSIRSSYEQYF", "CASSIRSYEQYF"),
#'     v_dist_a = v_alpha_mat,
#'     v_dist_b = v_beta_mat
#'   )
#' }
#' @export
rcpp_tcrdist_matrix <- function(va_genes, cdr3a_seqs, vb_genes, cdr3b_seqs, v_dist_a, v_dist_b, weight_cdr3_region = 3L, gap_penalty_cdr3_region = 12L) {
    .Call(`_tcrdistR_rcpp_tcrdist_matrix`, va_genes, cdr3a_seqs, vb_genes, cdr3b_seqs, v_dist_a, v_dist_b, weight_cdr3_region, gap_penalty_cdr3_region)
}

#' Compute pairwise V-region distances (C++ implementation)
#'
#' Computes all pairwise \code{blosum_sequence_distance} values for a set of
#' V-gene CDR loop sequences, weighted by \code{weight_v_region}.  Matches
#' the inner loop of \code{compute_all_v_region_distances()} in
#' \code{rconga/R/tcr_distances.R}.
#'
#' The sequences in \code{loop_seqs} are pre-aligned merged CDR loop strings
#' (CDRs joined by \code{" "}), as produced by the R gene-database loader.
#' Spaces mark position padding and are skipped (both positions must be space).
#'
#' @param gene_ids Character vector of length N. V-gene allele identifiers
#'   (e.g. \code{"TRAV1-1*01"}).  Used as row/column names of the result.
#' @param loop_seqs Character vector of length N.  Pre-aligned merged CDR loop
#'   sequences corresponding to each gene in \code{gene_ids}.  All sequences
#'   must have the same character length.
#' @param weight_v_region Numeric. Multiplied by each raw
#'   \code{blosum_sequence_distance} value.  Default 1.0 matches
#'   \code{WEIGHT_V_REGION}.
#' @param gap_penalty_v_region Numeric. Forwarded to
#'   \code{rcpp_blosum_sequence_distance} as \code{gap_penalty}.  Default 4.0
#'   matches \code{GAP_PENALTY_V_REGION}.
#' @return A named symmetric N x N \code{NumericMatrix}.
#'   \code{result[i, j] = weight_v_region * blosum_sequence_distance(loop_seqs[i], loop_seqs[j])}.
#' @examples
#' \dontrun{
#'   ids  <- c("TRAV1-1*01", "TRAV1-2*01")
#'   seqs <- c("ACDE FGHI", "ACDE FGHK")
#'   rcpp_compute_v_region_distances(ids, seqs)
#' }
#' @export
rcpp_compute_v_region_distances <- function(gene_ids, loop_seqs, weight_v_region = 1.0, gap_penalty_v_region = 4.0) {
    .Call(`_tcrdistR_rcpp_compute_v_region_distances`, gene_ids, loop_seqs, weight_v_region, gap_penalty_v_region)
}

