# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build the BSD4 amino acid distance matrix (C++ constexpr values)
#'
#' Returns the 20x20 BSD4 distance matrix derived from BLOSUM62 using the
#' CoNGA transformation:
#' \itemize{
#'   \item diagonal (a == b): 0
#'   \item off-diagonal, BLOSUM62 < 0: 4
#'   \item off-diagonal, BLOSUM62 >= 0: 4 - BLOSUM62
#' }
#' Row and column names follow alphabetical single-letter amino acid order
#' (A C D E F G H I K L M N P Q R S T V W Y), matching \code{AMINO_ACIDS}
#' in rconga.
#'
#' The values are compiled into the package as \code{constexpr} C++ arrays;
#' this function exposes them to R for verification and for use by any R
#' code that needs the matrix.
#'
#' @return A named 20x20 \code{NumericMatrix} of BSD4 distances.
#' @examples
#' \dontrun{
#'   bsd4 <- rcpp_build_bsd4()
#'   bsd4["A", "S"]  # 3 (BLOSUM62[A,S]=1, BSD4=4-1=3)
#'   bsd4["A", "A"]  # 0 (diagonal)
#'   bsd4["A", "C"]  # 4 (BLOSUM62=-something negative)
#' }
#' @export
rcpp_build_bsd4 <- function() {
    .Call(`_tcrdistR_rcpp_build_bsd4`)
}

#' Look up a single BLOSUM62 score for two amino acids
#'
#' @param aa1 Single-letter amino acid code (length-1 character string).
#' @param aa2 Single-letter amino acid code (length-1 character string).
#' @return Integer BLOSUM62 score for the pair.
#' @keywords internal
rcpp_blosum62_lookup <- function(aa1, aa2) {
    .Call(`_tcrdistR_rcpp_blosum62_lookup`, aa1, aa2)
}

#' K-nearest-neighbors from a precomputed distance matrix (C++ implementation)
#'
#' For each row of a square distance matrix \code{D}, finds the K nearest
#' neighbors while masking out entries that share the same alpha-chain or
#' beta-chain group assignment.  Same-group pairs are assigned the sentinel
#' distance 1e3 before selection.
#'
#' Uses \code{std::nth_element} for O(N) partial sorting per row, optionally
#' followed by \code{std::sort} of the K selected neighbors.
#'
#' @param D Numeric matrix (N x N). Precomputed pairwise distance matrix.
#'   Must be square.
#' @param K Integer. Number of nearest neighbors to extract per row.
#' @param agroups Integer vector of length N. Alpha-chain group assignments.
#'   Rows sharing the same agroups value are masked from each other.
#' @param bgroups Integer vector of length N. Beta-chain group assignments.
#'   Rows sharing the same bgroups value are masked from each other.
#' @param sort_nbrs Logical. If \code{TRUE}, sort the K neighbors by ascending
#'   distance.  Default \code{TRUE}.
#' @return A \code{List} with two elements:
#'   \describe{
#'     \item{\code{knn_indices}}{Integer matrix (N x K). 1-based neighbor indices.}
#'     \item{\code{knn_distances}}{Numeric matrix (N x K). Corresponding distances.}
#'   }
#' @examples
#' \dontrun{
#'   D <- matrix(c(0,1,2,1,0,3,2,3,0), nrow=3)
#'   result <- rcpp_knn_from_distance_matrix(D, K=1L, agroups=1:3, bgroups=1:3)
#' }
#' @export
rcpp_knn_from_distance_matrix <- function(D, K, agroups, bgroups, sort_nbrs = TRUE) {
    .Call(`_tcrdistR_rcpp_knn_from_distance_matrix`, D, K, agroups, bgroups, sort_nbrs)
}

#' K-nearest-neighbors from a PCA embedding matrix (C++ implementation)
#'
#' Computes K nearest neighbors directly from PCA embeddings (N x D matrix)
#' without materializing the full N x N Euclidean distance matrix.  For each
#' row, computes Euclidean distances to all N points on the fly, applies
#' group masking, and extracts the K nearest via \code{std::nth_element}.
#'
#' Memory: O(N*D + N*K) instead of O(N^2).
#'
#' @param pca_matrix Numeric matrix (N x D). PCA or other embedding coordinates.
#'   Rows are samples, columns are dimensions.
#' @param K Integer. Number of nearest neighbors to extract per point.
#' @param agroups Integer vector of length N. Alpha-chain group assignments.
#' @param bgroups Integer vector of length N. Beta-chain group assignments.
#' @param sort_nbrs Logical. If \code{TRUE}, sort the K neighbors by ascending
#'   Euclidean distance.  Default \code{TRUE}.
#' @return A \code{List} with two elements:
#'   \describe{
#'     \item{\code{knn_indices}}{Integer matrix (N x K). 1-based neighbor indices.}
#'     \item{\code{knn_distances}}{Numeric matrix (N x K). Euclidean distances.}
#'   }
#' @examples
#' \dontrun{
#'   pca <- matrix(rnorm(30), nrow=10, ncol=3)
#'   result <- rcpp_knn_from_pca_matrix(pca, K=3L, agroups=1:10, bgroups=1:10)
#' }
#' @export
rcpp_knn_from_pca_matrix <- function(pca_matrix, K, agroups, bgroups, sort_nbrs = TRUE) {
    .Call(`_tcrdistR_rcpp_knn_from_pca_matrix`, pca_matrix, K, agroups, bgroups, sort_nbrs)
}

rcpp_poisson_test_loop <- function(all_nbr_indices, all_nbr_distances, bg_freqs, agroups, bgroups, radii, n_bg_pairs, pvalue_threshold, num_clones, clusters_gex_nullable, use_conservative_pvalues) {
    .Call(`_tcrdistR_rcpp_poisson_test_loop`, all_nbr_indices, all_nbr_distances, bg_freqs, agroups, bgroups, radii, n_bg_pairs, pvalue_threshold, num_clones, clusters_gex_nullable, use_conservative_pvalues)
}

#' Count nucleotide prefix matches between two sequences (C++ implementation)
#'
#' Linear scan prefix matching: +1 per match, mismatch_score per mismatch.
#' Returns the length of the best-scoring prefix (the position at which the
#' cumulative score was highest).
#'
#' @param a Character string. First nucleotide sequence.
#' @param b Character string. Second nucleotide sequence.
#' @param mismatch_score Integer. Score added per mismatch position.
#'   Default -4.
#' @return Integer: length of best-scoring prefix (0 if either string is
#'   empty).
#' @examples
#' \dontrun{
#'   rcpp_count_nuc_matches("ATCGATCG", "ATCGTTCG")
#' }
#' @export
rcpp_count_nuc_matches <- function(a, b, mismatch_score = -4L) {
    .Call(`_tcrdistR_rcpp_count_nuc_matches`, a, b, mismatch_score)
}

#' Find alternate alleles for a batch of TCRs (C++ implementation)
#'
#' For each paired TCR (alpha+beta chains), tries alternate V/J alleles
#' (same gene, different allele number after \code{*}) and picks the allele
#' whose CDR3 nucleotide prefix match score improves by at least
#' \code{min_improvement} over the current allele.  J alleles are compared
#' using reversed sequences.
#'
#' @param va_genes Character vector. Alpha V gene names.
#' @param ja_genes Character vector. Alpha J gene names.
#' @param cdr3a_nucseqs Character vector. Alpha CDR3 nucleotide sequences.
#' @param vb_genes Character vector. Beta V gene names.
#' @param jb_genes Character vector. Beta J gene names.
#' @param cdr3b_nucseqs Character vector. Beta CDR3 nucleotide sequences.
#' @param all_gene_names Character vector. All gene names in the database.
#' @param all_v_cdr3_nucseqs Character vector. Pre-computed V CDR3 nucleotide
#'   sequences (same order as \code{all_gene_names}).
#' @param all_j_cdr3_nucseqs Character vector. Pre-computed J CDR3 nucleotide
#'   sequences (same order as \code{all_gene_names}).
#' @param mismatch_score Integer. Mismatch penalty for prefix scoring.
#'   Default -4.
#' @param min_improvement Integer. Minimum score improvement required to
#'   accept an alternate allele over the current one. Default 2.
#' @return A list with elements: \code{new_va}, \code{new_ja}, \code{new_vb},
#'   \code{new_jb} (character vectors), and \code{counts} (data.frame with
#'   columns \code{old_gene}, \code{new_gene}, \code{count}).
#' @examples
#' \dontrun{
#'   result <- rcpp_find_alternate_alleles_batch(
#'     va_genes, ja_genes, cdr3a_nucseqs,
#'     vb_genes, jb_genes, cdr3b_nucseqs,
#'     all_gene_names, all_v_cdr3_nucseqs, all_j_cdr3_nucseqs
#'   )
#' }
#' @export
rcpp_find_alternate_alleles_batch <- function(va_genes, ja_genes, cdr3a_nucseqs, vb_genes, jb_genes, cdr3b_nucseqs, all_gene_names, all_v_cdr3_nucseqs, all_j_cdr3_nucseqs, mismatch_score = -4L, min_improvement = 2L) {
    .Call(`_tcrdistR_rcpp_find_alternate_alleles_batch`, va_genes, ja_genes, cdr3a_nucseqs, vb_genes, jb_genes, cdr3b_nucseqs, all_gene_names, all_v_cdr3_nucseqs, all_j_cdr3_nucseqs, mismatch_score, min_improvement)
}

#' Resample shuffled TCR chains by junction breakpoint splicing (C++ implementation)
#'
#' Randomly selects pairs of junctions, finds shared breakpoints, and splices
#' chimeric nucleotide sequences.  Validates that the result has a length
#' divisible by 3 and contains no stop codons, then translates to amino acid.
#'
#' Uses an inline standard genetic code table (no external codon map needed).
#'
#' @param junction_v_genes Character vector. V gene names for each junction.
#' @param junction_j_genes Character vector. J gene names for each junction.
#' @param junction_nucseqs Character vector. CDR3 nucleotide sequences.
#' @param junction_breakpoints_pre_d List of integer vectors. Pre-D breakpoints
#'   for each junction.
#' @param junction_breakpoints_post_d List of integer vectors. Post-D
#'   breakpoints for each junction.
#' @param chain Character string. \code{"A"} for alpha (pre-D breakpoints only)
#'   or \code{"B"} for beta (both pre-D and post-D).
#' @param num_samples Integer. Number of chimeric TCRs to generate.
#' @param max_attempts Integer. Maximum sampling attempts before returning
#'   partial results.
#' @return A data.frame with columns: \code{v_gene}, \code{j_gene},
#'   \code{cdr3} (amino acid), \code{cdr3_nucseq}.
#' @examples
#' \dontrun{
#'   result <- rcpp_resample_shuffled_tcr_chains(
#'     v_genes, j_genes, nucseqs, bp_pre, bp_post, "B", 1000L, 100000L
#'   )
#' }
#' @export
rcpp_resample_shuffled_tcr_chains <- function(junction_v_genes, junction_j_genes, junction_nucseqs, junction_breakpoints_pre_d, junction_breakpoints_post_d, chain, num_samples, max_attempts) {
    .Call(`_tcrdistR_rcpp_resample_shuffled_tcr_chains`, junction_v_genes, junction_j_genes, junction_nucseqs, junction_breakpoints_pre_d, junction_breakpoints_post_d, chain, num_samples, max_attempts)
}

rcpp_calc_background_distributions <- function(fg_va, fg_cdr3a, fg_vb, fg_cdr3b, bg_va, bg_cdr3a, bg_vb, bg_cdr3b, v_dist_a, v_dist_b, max_dist, pseudocount = 0.25, weight_cdr3_region = 3L, gap_penalty_cdr3_region = 12L) {
    .Call(`_tcrdistR_rcpp_calc_background_distributions`, fg_va, fg_cdr3a, fg_vb, fg_cdr3b, bg_va, bg_cdr3a, bg_vb, bg_cdr3b, v_dist_a, v_dist_b, max_dist, pseudocount, weight_cdr3_region, gap_penalty_cdr3_region)
}

#' Weighted CDR3 distance (C++ implementation)
#'
#' Direct C++ port of the CDR3 distance algorithm from
#' \code{rconga/src/tcrdist_rcpp.cpp}.  Uses hard-coded \code{ntrim = 3},
#' \code{ctrim = 2} (\code{TRIM_CDR3S = TRUE}) and the fixed gap position
#' formula \code{min(6, 3 + (lenshort - 5) %/% 2)} (\code{ALIGN_CDR3S =
#' FALSE}).
#'
#' BSD4 values are compiled in as \code{constexpr} (no matrix argument
#' needed).  The result is numerically identical to
#' \code{rconga::rcpp_weighted_cdr3_distance()} for valid inputs.
#'
#' @param seq1 Character string. First CDR3 amino acid sequence.
#' @param seq2 Character string. Second CDR3 amino acid sequence.
#' @param weight_cdr3_region Integer. Multiplied by the raw alignment distance.
#'   Default 3 matches \code{WEIGHT_CDR3_REGION}.
#' @param gap_penalty_cdr3_region Integer. Per-residue length-difference penalty.
#'   Default 12 matches \code{GAP_PENALTY_CDR3_REGION}.
#' @return Numeric scalar: the weighted CDR3 distance.
#' @examples
#' \dontrun{
#'   rcpp_weighted_cdr3_distance("CASSIRSSYEQYF", "CASSIRSYEQYF")
#' }
#' @export
rcpp_weighted_cdr3_distance <- function(seq1, seq2, weight_cdr3_region = 3L, gap_penalty_cdr3_region = 12L) {
    .Call(`_tcrdistR_rcpp_weighted_cdr3_distance`, seq1, seq2, weight_cdr3_region, gap_penalty_cdr3_region)
}

#' Aligned sequence distance using BSD4 substitution costs (C++ implementation)
#'
#' Computes the total BSD4 distance between two pre-aligned amino acid strings
#' of equal length.  Matches \code{blosum_sequence_distance()} in
#' \code{rconga/R/tcr_distances.R} exactly.
#'
#' Position handling:
#' \itemize{
#'   \item Both characters are \code{" "} (space): position skipped (padding).
#'     The function stops with an error if only one character is a space.
#'   \item Both characters are \code{"."} (gap): distance 0.
#'   \item Both characters are \code{"*"} (stop codon): distance 0.
#'   \item One character is \code{"."} or \code{"*"}: \code{gap_penalty}.
#'   \item Both are valid amino acids: BSD4 lookup from the constexpr table.
#' }
#'
#' @param seq1 Character string. Aligned sequence (may contain \code{" "},
#'   \code{"."}, or \code{"*"}).
#' @param seq2 Character string. Aligned sequence of the same length as
#'   \code{seq1}.
#' @param gap_penalty Numeric. Applied when exactly one position is a gap or
#'   stop-codon character. Default 4.0 matches \code{GAP_PENALTY_V_REGION}.
#' @return Numeric scalar: sum of per-position BSD4 distances.
#' @examples
#' \dontrun{
#'   rcpp_blosum_sequence_distance("ACDE", "ACDF")
#' }
#' @export
rcpp_blosum_sequence_distance <- function(seq1, seq2, gap_penalty = 4.0) {
    .Call(`_tcrdistR_rcpp_blosum_sequence_distance`, seq1, seq2, gap_penalty)
}

#' K-nearest-neighbors by TCRdist with group masking (C++ implementation)
#'
#' For each of the N input TCRs, finds the K nearest neighbors by TCRdist
#' while masking out TCRs that share the same alpha-group or beta-group
#' assignment (same-group exclusion).  Same-group pairs and self-pairs are
#' assigned the sentinel distance 1e3 before selection.
#'
#' Uses \code{std::nth_element} for O(N) partial sorting per row, optionally
#' followed by O(K log K) full sorting of the K selected neighbors.
#' \code{Rcpp::checkUserInterrupt()} is called every 100 rows.
#'
#' @param va_genes   Character vector of length N. Alpha V-gene allele names.
#' @param cdr3a_seqs Character vector of length N. Alpha CDR3 sequences.
#' @param vb_genes   Character vector of length N. Beta V-gene allele names.
#' @param cdr3b_seqs Character vector of length N. Beta CDR3 sequences.
#' @param v_dist_a   Named square \code{NumericMatrix}. Pre-computed pairwise
#'   V-region distances for alpha genes.
#' @param v_dist_b   Named square \code{NumericMatrix}. Pre-computed pairwise
#'   V-region distances for beta genes.
#' @param K Integer. Number of nearest neighbors to return per TCR.
#' @param agroups Integer vector of length N. Alpha-chain group assignments.
#'   TCRs sharing the same agroups value are masked from each other.
#' @param bgroups Integer vector of length N. Beta-chain group assignments.
#'   TCRs sharing the same bgroups value are masked from each other.
#' @param sort_nbrs Logical. If \code{TRUE}, sort the K neighbors by ascending
#'   distance. Default \code{TRUE}.
#' @param weight_cdr3_region Integer. CDR3 alignment distance multiplier.
#'   Default 3 matches \code{WEIGHT_CDR3_REGION}.
#' @param gap_penalty_cdr3_region Integer. Per-residue length-difference
#'   penalty. Default 12 matches \code{GAP_PENALTY_CDR3_REGION}.
#' @return A \code{List} with two elements:
#'   \describe{
#'     \item{\code{knn_indices}}{Integer matrix (N x K). 1-based neighbor indices.}
#'     \item{\code{knn_distances}}{Numeric matrix (N x K). Corresponding distances.}
#'   }
#' @examples
#' \dontrun{
#'   result <- rcpp_tcrdist_knn(
#'     va_genes = c("TRAV1-1*01", "TRAV1-2*01"),
#'     cdr3a_seqs = c("CAVSANSGTYF", "CAVSANSGTYF"),
#'     vb_genes = c("TRBV20-1*01", "TRBV20-1*01"),
#'     cdr3b_seqs = c("CASSIRSSYEQYF", "CASSIRSYEQYF"),
#'     v_dist_a = v_alpha_mat, v_dist_b = v_beta_mat,
#'     K = 1L,
#'     agroups = 1:2, bgroups = 1:2
#'   )
#' }
#' @export
rcpp_tcrdist_knn <- function(va_genes, cdr3a_seqs, vb_genes, cdr3b_seqs, v_dist_a, v_dist_b, K, agroups, bgroups, sort_nbrs = TRUE, weight_cdr3_region = 3L, gap_penalty_cdr3_region = 12L) {
    .Call(`_tcrdistR_rcpp_tcrdist_knn`, va_genes, cdr3a_seqs, vb_genes, cdr3b_seqs, v_dist_a, v_dist_b, K, agroups, bgroups, sort_nbrs, weight_cdr3_region, gap_penalty_cdr3_region)
}

#' Pairwise TCRdist matrix (C++ implementation)
#'
#' Computes the full N x N symmetric matrix of paired-chain TCRdist distances.
#' For each pair \code{(i, j)}:
#' \deqn{
#'   d(i,j) = v\_dist\_a[va_i, va_j] + cdr3\_dist(cdr3a_i, cdr3a_j)
#'           + v\_dist\_b[vb_i, vb_j] + cdr3\_dist(cdr3b_i, cdr3b_j)
#' }
#'
#' Only the upper triangle is computed; it is mirrored to the lower triangle.
#' The diagonal is zero.  \code{Rcpp::checkUserInterrupt()} is called every
#' 100 outer-loop rows to allow the user to interrupt long computations.
#'
#' BSD4 values are compiled in as \code{constexpr}; no \code{bsd4} matrix
#' argument is needed (unlike the rconga equivalent).
#'
#' @param va_genes   Character vector of length N. Alpha V-gene allele names.
#' @param cdr3a_seqs Character vector of length N. Alpha CDR3 sequences.
#' @param vb_genes   Character vector of length N. Beta V-gene allele names.
#' @param cdr3b_seqs Character vector of length N. Beta CDR3 sequences.
#' @param v_dist_a   Named square \code{NumericMatrix}. Pre-computed pairwise
#'   V-region distances for alpha genes (row/column names are V-gene allele
#'   strings, e.g. \code{"TRAV1-1*01"}).
#' @param v_dist_b   Named square \code{NumericMatrix}. Same structure for
#'   beta genes.
#' @param weight_cdr3_region Integer. CDR3 alignment distance multiplier.
#'   Default 3 matches \code{WEIGHT_CDR3_REGION}.
#' @param gap_penalty_cdr3_region Integer. Per-residue length-difference
#'   penalty.  Default 12 matches \code{GAP_PENALTY_CDR3_REGION}.
#' @return An N x N symmetric \code{NumericMatrix} of TCRdist distances.
#' @examples
#' \dontrun{
#'   mat <- rcpp_tcrdist_matrix(
#'     va_genes = c("TRAV1-1*01", "TRAV1-2*01"),
#'     cdr3a_seqs = c("CAVSANSGTYF", "CAVSANSGTYF"),
#'     vb_genes = c("TRBV20-1*01", "TRBV20-1*01"),
#'     cdr3b_seqs = c("CASSIRSSYEQYF", "CASSIRSYEQYF"),
#'     v_dist_a = v_alpha_mat,
#'     v_dist_b = v_beta_mat
#'   )
#' }
#' @export
rcpp_tcrdist_matrix <- function(va_genes, cdr3a_seqs, vb_genes, cdr3b_seqs, v_dist_a, v_dist_b, weight_cdr3_region = 3L, gap_penalty_cdr3_region = 12L) {
    .Call(`_tcrdistR_rcpp_tcrdist_matrix`, va_genes, cdr3a_seqs, vb_genes, cdr3b_seqs, v_dist_a, v_dist_b, weight_cdr3_region, gap_penalty_cdr3_region)
}

#' Radius-based TCRdist neighbor search with group masking (C++ implementation)
#'
#' For each of the N input TCRs, finds all other TCRs within \code{radius}
#' TCRdist distance, excluding TCRs that share the same alpha or beta group
#' (same-group exclusion) and self-pairs.
#'
#' Three-stage early termination is applied per pair:
#' \enumerate{
#'   \item If V-region distance alone exceeds \code{radius}, skip.
#'   \item If V-region + CDR3-alpha distance exceeds \code{radius}, skip.
#'   \item If full distance exceeds \code{radius}, skip.
#' }
#'
#' \code{Rcpp::checkUserInterrupt()} is called every 100 rows.
#'
#' @param va_genes   Character vector of length N. Alpha V-gene allele names.
#' @param cdr3a_seqs Character vector of length N. Alpha CDR3 sequences.
#' @param vb_genes   Character vector of length N. Beta V-gene allele names.
#' @param cdr3b_seqs Character vector of length N. Beta CDR3 sequences.
#' @param v_dist_a   Named square \code{NumericMatrix}. Pre-computed pairwise
#'   V-region distances for alpha genes.
#' @param v_dist_b   Named square \code{NumericMatrix}. Pre-computed pairwise
#'   V-region distances for beta genes.
#' @param radius     Numeric. Search radius. Only neighbors within this
#'   distance (inclusive) are returned.
#' @param agroups Integer vector of length N. Alpha-chain group assignments.
#' @param bgroups Integer vector of length N. Beta-chain group assignments.
#' @param weight_cdr3_region Integer. CDR3 alignment distance multiplier.
#'   Default 3 matches \code{WEIGHT_CDR3_REGION}.
#' @param gap_penalty_cdr3_region Integer. Per-residue length-difference
#'   penalty. Default 12 matches \code{GAP_PENALTY_CDR3_REGION}.
#' @return A \code{List} of length N. Each element is a \code{List} with:
#'   \describe{
#'     \item{\code{indices}}{Integer vector of 1-based neighbor indices.}
#'     \item{\code{distances}}{Numeric vector of corresponding distances.}
#'   }
#' @examples
#' \dontrun{
#'   result <- rcpp_tcrdist_radius_neighbors(
#'     va_genes = c("TRAV1-1*01", "TRAV1-2*01"),
#'     cdr3a_seqs = c("CAVSANSGTYF", "CAVSANSGTYF"),
#'     vb_genes = c("TRBV20-1*01", "TRBV20-1*01"),
#'     cdr3b_seqs = c("CASSIRSSYEQYF", "CASSIRSYEQYF"),
#'     v_dist_a = v_alpha_mat, v_dist_b = v_beta_mat,
#'     radius = 50, agroups = 1:2, bgroups = 1:2
#'   )
#' }
#' @export
rcpp_tcrdist_radius_neighbors <- function(va_genes, cdr3a_seqs, vb_genes, cdr3b_seqs, v_dist_a, v_dist_b, radius, agroups, bgroups, weight_cdr3_region = 3L, gap_penalty_cdr3_region = 12L) {
    .Call(`_tcrdistR_rcpp_tcrdist_radius_neighbors`, va_genes, cdr3a_seqs, vb_genes, cdr3b_seqs, v_dist_a, v_dist_b, radius, agroups, bgroups, weight_cdr3_region, gap_penalty_cdr3_region)
}

#' Rectangular TCRdist query-vs-reference distance matrix (C++ implementation)
#'
#' Computes an nq x nr matrix of paired-chain TCRdist distances between a
#' query set of \code{nq} TCRs and a reference set of \code{nr} TCRs.
#' For each query-reference pair \code{(i, j)}:
#' \deqn{
#'   d(i,j) = v\_dist\_a[va\_query_i, va\_ref_j]
#'           + cdr3\_dist(cdr3a\_query_i, cdr3a\_ref_j)
#'           + v\_dist\_b[vb\_query_i, vb\_ref_j]
#'           + cdr3\_dist(cdr3b\_query_i, cdr3b\_ref_j)
#' }
#'
#' No symmetry is exploited; all nq * nr distances are computed.
#' \code{Rcpp::checkUserInterrupt()} is called every 100 outer-loop rows.
#'
#' @param query_va   Character vector of length nq. Query alpha V-gene alleles.
#' @param query_cdr3a Character vector of length nq. Query alpha CDR3 sequences.
#' @param query_vb   Character vector of length nq. Query beta V-gene alleles.
#' @param query_cdr3b Character vector of length nq. Query beta CDR3 sequences.
#' @param ref_va     Character vector of length nr. Reference alpha V-gene alleles.
#' @param ref_cdr3a  Character vector of length nr. Reference alpha CDR3 sequences.
#' @param ref_vb     Character vector of length nr. Reference beta V-gene alleles.
#' @param ref_cdr3b  Character vector of length nr. Reference beta CDR3 sequences.
#' @param v_dist_a   Named square \code{NumericMatrix}. Pre-computed pairwise
#'   V-region distances for alpha genes.
#' @param v_dist_b   Named square \code{NumericMatrix}. Pre-computed pairwise
#'   V-region distances for beta genes.
#' @param weight_cdr3_region Integer. CDR3 alignment distance multiplier.
#'   Default 3 matches \code{WEIGHT_CDR3_REGION}.
#' @param gap_penalty_cdr3_region Integer. Per-residue length-difference
#'   penalty. Default 12 matches \code{GAP_PENALTY_CDR3_REGION}.
#' @return An nq x nr \code{NumericMatrix} of TCRdist distances.
#' @examples
#' \dontrun{
#'   mat <- rcpp_tcrdist_rect(
#'     query_va = c("TRAV1-1*01"),
#'     query_cdr3a = c("CAVSANSGTYF"),
#'     query_vb = c("TRBV20-1*01"),
#'     query_cdr3b = c("CASSIRSSYEQYF"),
#'     ref_va = c("TRAV1-1*01", "TRAV1-2*01"),
#'     ref_cdr3a = c("CAVSANSGTYF", "CAVSANSGTYF"),
#'     ref_vb = c("TRBV20-1*01", "TRBV20-1*01"),
#'     ref_cdr3b = c("CASSIRSSYEQYF", "CASSIRSYEQYF"),
#'     v_dist_a = v_alpha_mat,
#'     v_dist_b = v_beta_mat
#'   )
#' }
#' @export
rcpp_tcrdist_rect <- function(query_va, query_cdr3a, query_vb, query_cdr3b, ref_va, ref_cdr3a, ref_vb, ref_cdr3b, v_dist_a, v_dist_b, weight_cdr3_region = 3L, gap_penalty_cdr3_region = 12L) {
    .Call(`_tcrdistR_rcpp_tcrdist_rect`, query_va, query_cdr3a, query_vb, query_cdr3b, ref_va, ref_cdr3a, ref_vb, ref_cdr3b, v_dist_a, v_dist_b, weight_cdr3_region, gap_penalty_cdr3_region)
}

#' Sparse TCRdist matrix as COO triplets (C++ implementation)
#'
#' Computes pairwise TCRdist distances for all (i, j) pairs with i < j and
#' distance <= \code{threshold}, returning a sparse representation in
#' coordinate (COO) format.
#'
#' Three-stage early termination is used to skip pairs that cannot satisfy
#' the threshold:
#' \enumerate{
#'   \item If V-region distance alone exceeds threshold, skip.
#'   \item If V-region + CDR3-alpha distance exceeds threshold, skip.
#'   \item If full distance exceeds threshold, skip.
#' }
#'
#' \code{Rcpp::checkUserInterrupt()} is called every 100 outer-loop rows.
#'
#' @param va_genes   Character vector of length N. Alpha V-gene allele names.
#' @param cdr3a_seqs Character vector of length N. Alpha CDR3 sequences.
#' @param vb_genes   Character vector of length N. Beta V-gene allele names.
#' @param cdr3b_seqs Character vector of length N. Beta CDR3 sequences.
#' @param v_dist_a   Named square \code{NumericMatrix}. Pre-computed pairwise
#'   V-region distances for alpha genes.
#' @param v_dist_b   Named square \code{NumericMatrix}. Pre-computed pairwise
#'   V-region distances for beta genes.
#' @param threshold  Numeric. Maximum distance to include in the result.
#'   Pairs with distance > threshold are omitted.
#' @param weight_cdr3_region Integer. CDR3 alignment distance multiplier.
#'   Default 3 matches \code{WEIGHT_CDR3_REGION}.
#' @param gap_penalty_cdr3_region Integer. Per-residue length-difference
#'   penalty. Default 12 matches \code{GAP_PENALTY_CDR3_REGION}.
#' @return A \code{List} with four elements:
#'   \describe{
#'     \item{\code{i}}{Integer vector of 1-based row indices.}
#'     \item{\code{j}}{Integer vector of 1-based column indices.}
#'     \item{\code{x}}{Numeric vector of distance values.}
#'     \item{\code{n}}{Integer scalar: matrix dimension (N).}
#'   }
#' @examples
#' \dontrun{
#'   triplets <- rcpp_tcrdist_sparse(
#'     va_genes = c("TRAV1-1*01", "TRAV1-2*01"),
#'     cdr3a_seqs = c("CAVSANSGTYF", "CAVSANSGTYF"),
#'     vb_genes = c("TRBV20-1*01", "TRBV20-1*01"),
#'     cdr3b_seqs = c("CASSIRSSYEQYF", "CASSIRSYEQYF"),
#'     v_dist_a = v_alpha_mat, v_dist_b = v_beta_mat,
#'     threshold = 50
#'   )
#' }
#' @export
rcpp_tcrdist_sparse <- function(va_genes, cdr3a_seqs, vb_genes, cdr3b_seqs, v_dist_a, v_dist_b, threshold, weight_cdr3_region = 3L, gap_penalty_cdr3_region = 12L) {
    .Call(`_tcrdistR_rcpp_tcrdist_sparse`, va_genes, cdr3a_seqs, vb_genes, cdr3b_seqs, v_dist_a, v_dist_b, threshold, weight_cdr3_region, gap_penalty_cdr3_region)
}

#' Compute pairwise V-region distances (C++ implementation)
#'
#' Computes all pairwise \code{blosum_sequence_distance} values for a set of
#' V-gene CDR loop sequences, weighted by \code{weight_v_region}.  Matches
#' the inner loop of \code{compute_all_v_region_distances()} in
#' \code{rconga/R/tcr_distances.R}.
#'
#' The sequences in \code{loop_seqs} are pre-aligned merged CDR loop strings
#' (CDRs joined by \code{" "}), as produced by the R gene-database loader.
#' Spaces mark position padding and are skipped (both positions must be space).
#'
#' @param gene_ids Character vector of length N. V-gene allele identifiers
#'   (e.g. \code{"TRAV1-1*01"}).  Used as row/column names of the result.
#' @param loop_seqs Character vector of length N.  Pre-aligned merged CDR loop
#'   sequences corresponding to each gene in \code{gene_ids}.  All sequences
#'   must have the same character length.
#' @param weight_v_region Numeric. Multiplied by each raw
#'   \code{blosum_sequence_distance} value.  Default 1.0 matches
#'   \code{WEIGHT_V_REGION}.
#' @param gap_penalty_v_region Numeric. Forwarded to
#'   \code{rcpp_blosum_sequence_distance} as \code{gap_penalty}.  Default 4.0
#'   matches \code{GAP_PENALTY_V_REGION}.
#' @return A named symmetric N x N \code{NumericMatrix}.
#'   \code{result[i, j] = weight_v_region * blosum_sequence_distance(loop_seqs[i], loop_seqs[j])}.
#' @examples
#' \dontrun{
#'   ids  <- c("TRAV1-1*01", "TRAV1-2*01")
#'   seqs <- c("ACDE FGHI", "ACDE FGHK")
#'   rcpp_compute_v_region_distances(ids, seqs)
#' }
#' @export
rcpp_compute_v_region_distances <- function(gene_ids, loop_seqs, weight_v_region = 1.0, gap_penalty_v_region = 4.0) {
    .Call(`_tcrdistR_rcpp_compute_v_region_distances`, gene_ids, loop_seqs, weight_v_region, gap_penalty_v_region)
}

